// Generated by karac for plume.wasm — TypeScript declarations for
// the browser-WASM glue module. DO NOT EDIT.

/** Trailing context argument passed to every host fn implementation. */
export interface HostCtx {
  readonly memory: WebAssembly.Memory;
  /** Decode a (ptr, len) UTF-8 string out of the module's linear memory. */
  readString(ptr: number | bigint, len: number | bigint): string;
}

/**
 * Host fn implementations (the `kara_host` import namespace).
 * i64/u64/isize/usize cross the boundary as bigint; every other
 * host-fn-legal scalar is a number; strings arrive as (ptr, len)
 * pairs — decode with `ctx.readString`.
 */
export interface HostImpls {
  /** `host fn put_pixels(ptr: *const u8, len: i64, w: i64, h: i64)` */
  put_pixels(ptr: number, len: bigint, w: bigint, h: bigint, ctx: HostCtx): void;
}

export interface InstantiateOpts {
  /** Pre-compiled module — bypasses the default loader.
   * Feeds the sequential path only. */
  module?: WebAssembly.Module;
  /** Raw module bytes — bypasses the default loader.
   * Feeds the sequential path only. */
  bytes?: BufferSource;
  /** Skip the threaded-module pick in run() and use the
   * sequential module unconditionally. */
  forceSequential?: boolean;
}

export interface KaraExports {
  _start(): void;
}

export interface KaraHandle {
  instance: WebAssembly.Instance;
  exports: WebAssembly.Exports & KaraExports;
  memory: WebAssembly.Memory;
}

/** Resolved by run() when the THREADED module was picked: the
 * program ran on the Web Worker pool (its instance lives in the
 * primary worker); only the shared memory crosses back. */
export interface KaraThreadedHandle {
  memory: WebAssembly.Memory;
  threaded: true;
}

/** Decode a (ptr, len) UTF-8 string out of the module's linear memory. */
export function readString(
  memory: WebAssembly.Memory,
  ptr: number | bigint,
  len: number | bigint,
): string;

/** Thrown by the WASI polyfill's proc_exit; run() swallows exit code 0. */
export class KaraExit extends Error {
  code: number;
  constructor(code: number);
}

/**
 * Compile + instantiate the SEQUENTIAL module (its exports run on
 * the caller's thread, which must never block — the threaded
 * module is only ever driven by run()'s worker pool). Missing
 * host fn implementations throw before any wasm runs.
 */
export function instantiate(
  hostImpls: HostImpls,
  opts?: InstantiateOpts,
): Promise<KaraHandle>;

/**
 * Run the program: picks the THREADED module when SharedArrayBuffer
 * + cross-origin isolation are available (deploy with COOP/COEP
 * headers), else console.warns and falls back to the sequential
 * module (or throws, when the build disabled fallback). A clean
 * exit resolves normally; a nonzero exit code rejects with KaraExit.
 */
export function run(
  hostImpls: HostImpls,
  opts?: InstantiateOpts,
): Promise<KaraHandle | KaraThreadedHandle>;
