// Generated by karac for mandelbrot.wasm — browser-WASM glue. DO NOT EDIT.
//
// The module is a wasm32-wasip1 command module; this file supplies a
// minimal console-backed WASI preview-1 polyfill plus the `kara_host`
// import namespace where `host fn` implementations live (a stable
// contract — hand-rolled hosts instantiate with
// `{ kara_host: {...}, wasi_snapshot_preview1: {...} }`).
//
// Boundary conventions: numeric scalars pass by value; i64/u64/
// isize/usize cross as BigInt; opaque handles cross at their declared
// scalar width; strings cross as (ptr, len) pairs — read them with
// readString. Each implementation receives one trailing context
// argument `{ memory, readString(ptr, len) }`.
//
// Declared host fns (implement each in the object passed to
// run/instantiate):
//   put_pixels(ptr: *const u8, len: i64 [BigInt], w: i64 [BigInt], h: i64 [BigInt])

//
// wasm-threads build: a second, threaded module ships alongside
// (Web Worker pool + SharedArrayBuffer + atomics). run() picks it
// at load time when SAB + cross-origin isolation are available —
// deploy with COOP/COEP headers:
//   Cross-Origin-Opener-Policy: same-origin
//   Cross-Origin-Embedder-Policy: require-corp
// instantiate() always uses the sequential module (its exports
// run on the caller's thread, which must never block).

const WASM_FILENAME = "mandelbrot.wasm";
const DECLARED_IMPORTS = ["put_pixels"];
const HOST_FN_SIGS = [{ name: "put_pixels", params: ["number", "bigint", "bigint", "bigint"], ret: "void" }, { name: "__kara_timer_after", params: ["bigint", "bigint"], ret: "void" }, { name: "__kara_animation_frames", params: ["bigint"], ret: "void" }, { name: "__kara_pointer_moves", params: ["bigint"], ret: "void" }, { name: "__kara_wheel", params: ["bigint"], ret: "void" }, { name: "__kara_keydown", params: ["bigint"], ret: "void" }];
const BUILTIN_HOST_FNS = ["__kara_timer_after", "__kara_animation_frames", "__kara_pointer_moves", "__kara_wheel", "__kara_keydown"];
const WASM_THREADS_FILENAME = "mandelbrot.threads.wasm";
const THREADS_NO_FALLBACK = false;
const THREADS_POOL_SIZE = null;
const THREADS_MEM_INITIAL_PAGES = 18;
const THREADS_MEM_MAX_PAGES = 16384;
const KARA_EXPORTS = [];

/** Decode a (ptr, len) UTF-8 string out of the module's linear memory.
 * `.slice()` copies into a fresh non-shared buffer first: on the threaded
 * (`--features wasm-threads`) build `memory.buffer` is a SharedArrayBuffer, and
 * browser `TextDecoder.decode` rejects shared views ("The provided
 * ArrayBufferView value must not be shared."). This helper is the single
 * string-decode funnel — it backs `ctx.readString` in the main-thread
 * host-service loop (a `host fn` taking a `string` arg) and the rich
 * string-export lift — so the copy must live here, not just at the fd_write
 * call site. B-2026-06-14-22 follow-up: 69c49ec0 fixed fd_write + random_get
 * but missed this helper; node's lenient TextDecoder hid it. Harmless (a copy)
 * on the sequential path where the buffer is already non-shared. */
export function readString(memory, ptr, len) {
  return new TextDecoder("utf-8").decode(
    new Uint8Array(memory.buffer, Number(ptr), Number(len)).slice(),
  );
}

// ── Rich-export marshalling (phase-10 WASM entry-point discovery) ──────
// KARA_EXPORTS (emitted above) describes each record/option/result/
// string/list export; the entries are interpreted here to marshal JS
// values across the canonical-ABI trampolines. Shape tags: 0 scalar,
// 1 record, 2 option, 3 result, 4 string, 5 list.

function karaScalarRead(dv, off, ty) {
  switch (ty) {
    case "i8": return dv.getInt8(off);
    case "u8": case "bool": return dv.getUint8(off);
    case "i16": return dv.getInt16(off, true);
    case "u16": return dv.getUint16(off, true);
    case "i32": case "char": return dv.getInt32(off, true);
    case "u32": return dv.getUint32(off, true);
    case "f32": return dv.getFloat32(off, true);
    case "f64": return dv.getFloat64(off, true);
    case "i64": case "isize": return dv.getBigInt64(off, true);
    case "u64": case "usize": return dv.getBigUint64(off, true);
    default: return dv.getInt32(off, true);
  }
}

function karaScalarWrite(dv, off, ty, v) {
  switch (ty) {
    case "i8": dv.setInt8(off, v); break;
    case "u8": case "bool": dv.setUint8(off, v); break;
    case "i16": dv.setInt16(off, v, true); break;
    case "u16": dv.setUint16(off, v, true); break;
    case "i32": case "char": dv.setInt32(off, v, true); break;
    case "u32": dv.setUint32(off, v, true); break;
    case "f32": dv.setFloat32(off, v, true); break;
    case "f64": dv.setFloat64(off, v, true); break;
    case "i64": case "isize": dv.setBigInt64(off, BigInt(v), true); break;
    case "u64": case "usize": dv.setBigUint64(off, BigInt(v), true); break;
    default: dv.setInt32(off, v, true); break;
  }
}

// Lift a canonical value at `ptr` (a return-area / inner pointer) into a
// JS value per `shape`.
function karaLift(memory, shape, ptr) {
  const dv = new DataView(memory.buffer);
  switch (shape.k) {
    case 0: return karaScalarRead(dv, ptr, shape.ty);
    case 1: {
      const o = {};
      for (const f of shape.f) o[f.n] = karaScalarRead(dv, ptr + f.o, f.ty);
      return o;
    }
    case 2:
      return dv.getUint8(ptr) === 1 ? karaLift(memory, shape.p, ptr + shape.po) : null;
    case 3:
      return dv.getUint8(ptr) === 0
        ? { ok: karaLift(memory, shape.ok, ptr + shape.po) }
        : { err: karaLift(memory, shape.err, ptr + shape.po) };
    case 4: {
      const sp = dv.getInt32(ptr, true), sl = dv.getInt32(ptr + 4, true);
      return readString(memory, sp, sl);
    }
    case 5: {
      const lp = dv.getInt32(ptr, true), lc = dv.getInt32(ptr + 4, true);
      const out = [];
      for (let i = 0; i < lc; i++) out.push(karaLift(memory, shape.e, lp + i * shape.es));
      return out;
    }
  }
}

// Lower a JS value to the trampoline's canonical flat params, pushing
// onto `flats`. `alloc(size, align)` reserves guest memory (cabi_realloc).
function karaLowerParam(memory, alloc, shape, val, flats) {
  switch (shape.k) {
    case 0:
      flats.push(val);
      break;
    case 1: // record → flattened field values, in declaration order
      for (const f of shape.f) flats.push(val[f.n]);
      break;
    case 4: { // string → (ptr, len)
      const bytes = new TextEncoder().encode(val);
      const p = alloc(bytes.length, 1);
      new Uint8Array(memory.buffer, p, bytes.length).set(bytes);
      flats.push(p, bytes.length);
      break;
    }
    case 5: { // list → (ptr, count)
      const n = val.length;
      const p = alloc(n * shape.es, shape.es);
      const dv = new DataView(memory.buffer);
      for (let i = 0; i < n; i++) karaScalarWrite(dv, p + i * shape.es, shape.e.ty, val[i]);
      flats.push(p, n);
      break;
    }
    default:
      throw new Error("kara: unsupported export param shape " + shape.k);
  }
}

// Build the handle's `exports`: rich exports (in KARA_EXPORTS) are wrapped
// to marshal JS values; everything else passes through `instance.exports`.
function karaBuildExports(instance) {
  const raw = instance.exports;
  const memory = raw.memory;
  // `instance.exports` is frozen (its props are read-only), so copy into
  // a writable object before overriding the rich exports with wrappers.
  const wrapped = Object.assign({}, raw);
  for (const sig of KARA_EXPORTS) {
    const fn = raw[sig.name];
    wrapped[sig.name] = (...args) => {
      const flats = [];
      const alloc = (sz, al) => raw.cabi_realloc(0, 0, al, sz);
      for (let i = 0; i < sig.params.length; i++) {
        karaLowerParam(memory, alloc, sig.params[i], args[i], flats);
      }
      const r = fn(...flats);
      if (sig.ret == null) return undefined;
      // A scalar return comes back by value; a record/option/result/
      // string/list return comes back as a canonical return-area pointer.
      return sig.ret.k === 0 ? r : karaLift(memory, sig.ret, r);
    };
  }
  return wrapped;
}

/** Thrown by the WASI polyfill's proc_exit; run() swallows exit code 0. */
export class KaraExit extends Error {
  constructor(code) {
    super(`proc_exit(${code})`);
    this.code = code;
  }
}

// Minimal console-backed WASI preview-1 polyfill — just enough for the
// karac wasm runtime archive (stdout/stderr writes, clock, randomness,
// args/environ negotiation). Unknown syscalls throw loudly by name.
// `env` is a list of "KEY=value" strings serialized through
// environ_get — the threaded path injects KARAC_PAR_WORKERS there (the
// runtime's pool-size knob); the sequential path passes none.
function makeWasiPolyfill(getMemory, env = []) {
  const view = () => new DataView(getMemory().buffer);
  const envBytes = env.map((s) => new TextEncoder().encode(s + "\0"));
  const impl = {
    fd_write(fd, iovsPtr, iovsLen, nwrittenPtr) {
      const dv = view();
      let written = 0;
      let text = "";
      for (let i = 0; i < iovsLen; i++) {
        const base = iovsPtr + i * 8;
        const ptr = dv.getUint32(base, true);
        const len = dv.getUint32(base + 4, true);
        // `.slice()` copies into a fresh non-shared ArrayBuffer: on the
        // threaded build `getMemory().buffer` is a SharedArrayBuffer, and
        // TextDecoder.decode rejects a shared-backed view ("The provided
        // ArrayBufferView value must not be shared."). Any stdout/stderr
        // write from a threaded browser program — a print, a panic, the
        // alloc-error abort path — hit this without the copy (B-2026-06-14-22).
        text += new TextDecoder("utf-8").decode(
          new Uint8Array(getMemory().buffer, ptr, len).slice(),
        );
        written += len;
      }
      dv.setUint32(nwrittenPtr, written, true);
      if (nodeFsSync) {
        // Threaded path under node: workers' console pipes to the main
        // process asynchronously and an unref'd pthread worker dying at
        // process exit drops anything unflushed — writeSync is the
        // loss-proof channel. Only ever set on the threaded path; the
        // sequential glue keeps the console behavior byte-for-byte.
        nodeFsSync.writeSync(fd === 2 ? 2 : 1, text);
      } else {
        (fd === 2 ? console.error : console.log)(text.replace(/\n$/, ""));
      }
      return 0;
    },
    fd_close() {
      return 0;
    },
    fd_seek() {
      return 70; // ESPIPE — the console streams are not seekable.
    },
    fd_fdstat_get(_fd, outPtr) {
      new Uint8Array(getMemory().buffer, outPtr, 24).fill(0);
      view().setUint8(outPtr, 2); // filetype: character_device
      return 0;
    },
    proc_exit(code) {
      throw new KaraExit(code);
    },
    clock_time_get(_id, _precision, outPtr) {
      const ns = BigInt(Math.round(performance.now() * 1e6));
      view().setBigUint64(outPtr, ns, true);
      return 0;
    },
    random_get(ptr, len) {
      // crypto.getRandomValues also rejects a SharedArrayBuffer-backed
      // view (threaded build), so fill a fresh non-shared buffer and copy
      // the bytes into linear memory.
      const tmp = new Uint8Array(len);
      globalThis.crypto.getRandomValues(tmp);
      new Uint8Array(getMemory().buffer, ptr, len).set(tmp);
      return 0;
    },
    args_sizes_get(argcPtr, argvBufSizePtr) {
      view().setUint32(argcPtr, 0, true);
      view().setUint32(argvBufSizePtr, 0, true);
      return 0;
    },
    args_get() {
      return 0;
    },
    environ_sizes_get(countPtr, bufSizePtr) {
      view().setUint32(countPtr, envBytes.length, true);
      view().setUint32(
        bufSizePtr,
        envBytes.reduce((a, b) => a + b.length, 0),
        true,
      );
      return 0;
    },
    environ_get(environPtr, bufPtr) {
      const dv = view();
      const mem = new Uint8Array(getMemory().buffer);
      let p = bufPtr;
      envBytes.forEach((b, i) => {
        dv.setUint32(environPtr + 4 * i, p, true);
        mem.set(b, p);
        p += b.length;
      });
      return 0;
    },
    sched_yield() {
      return 0;
    },
  };
  return new Proxy(impl, {
    get(target, prop) {
      if (prop in target) return target[prop];
      return () => {
        throw new Error(
          `WASI syscall not polyfilled by this glue: ${String(prop)}`,
        );
      };
    },
  });
}

function buildImports(hostImpls, getMemory) {
  const missing = DECLARED_IMPORTS.filter(
    (n) => typeof hostImpls?.[n] !== "function",
  );
  if (missing.length > 0) {
    throw new Error(
      "missing host fn implementation(s): " + missing.join(", "),
    );
  }
  const ctx = {
    get memory() {
      return getMemory();
    },
    readString: (ptr, len) => readString(getMemory(), ptr, len),
  };
  const kara_host = {};
  for (const name of DECLARED_IMPORTS) {
    kara_host[name] = (...args) => hostImpls[name](...args, ctx);
  }
  return { kara_host, wasi_snapshot_preview1: makeWasiPolyfill(getMemory) };
}

// Default loader: `new URL(..., import.meta.url)` is the asset-reference
// pattern bundlers (vite / webpack / esbuild / rollup) rewrite natively —
// no custom loader configuration. Under node (file: URL) read from disk.
async function defaultSource(filename = WASM_FILENAME) {
  const url = new URL(filename, import.meta.url);
  if (url.protocol === "file:") {
    const [{ readFile }, { fileURLToPath }] = await Promise.all([
      import("node:fs/promises"),
      import("node:url"),
    ]);
    return await readFile(fileURLToPath(url));
  }
  return await fetch(url);
}

// ── wasm-threads machinery (inert when WASM_THREADS_FILENAME is null) ──
//
// The threaded module is a wasm32-wasip1-threads build: shared imported
// memory (`env.memory`), pthreads riding the wasi-threads ABI — the
// module imports `wasi.thread-spawn` and exports `wasi_thread_start`;
// this glue services thread-spawn by spawning a Web Worker (browser) /
// worker_threads Worker (node) ON THIS SAME MODULE FILE, which detects
// the worker role at load and runs the worker protocol below.
//
// The program's `_start` itself runs in a "primary" worker — never on
// the page's main thread — because every blocking primitive in the
// threaded runtime bottoms out in `memory.atomic.wait32`, which traps
// on non-blockable agents (the browser main thread). The classic
// PROXY_TO_PTHREAD model.

/** SAB + cross-origin isolation feature detection. node has SAB
 * unconditionally and no crossOriginIsolated — treat undefined as
 * isolated. */
function threadsSupported() {
  if (typeof SharedArrayBuffer === "undefined") return false;
  return globalThis.crossOriginIsolated ?? true;
}

// node:worker_threads module, resolved once per agent (main thread at
// runThreaded; workers at bootstrap) so thread-spawn can create
// siblings synchronously.
let nodeWorkerThreads = null;
// node:fs, resolved alongside — gives the threaded path's fd_write a
// synchronous stdout/stderr (see the polyfill). Stays null on the
// sequential path and in browsers.
let nodeFsSync = null;

/** Spawn a kara thread worker on this module file. `data` is the
 * worker-protocol record (structured-cloneable: WebAssembly.Module,
 * shared Memory, SAB tid counter). Synchronous — wasi.thread-spawn
 * must return the new tid without awaiting. */
function spawnKaraWorkerSync(data, opts = {}) {
  if (nodeWorkerThreads) {
    const w = new nodeWorkerThreads.Worker(new URL(import.meta.url), {
      workerData: data,
    });
    // pthread workers must not hold the node process open — the pool's
    // worker_loop never returns by design (parity with the native
    // daemon-thread pool). The primary stays ref'd: its exit message is
    // the program result.
    if (opts.unref) w.unref();
    return w;
  }
  // The #kara-thread-worker fragment is the worker-role marker: only a
  // module loaded under it consumes its first message as the protocol
  // record, so a user importing this glue inside their own worker is
  // never disturbed.
  const w = new Worker(new URL("#kara-thread-worker", import.meta.url), {
    type: "module",
  });
  w.postMessage(data);
  return w;
}

// ── pthread-spawn worker→main proxy (browser only) ──
//
// In browsers, a nested dedicated worker's module script is fetched on its
// CREATING agent's event loop. A wasm pthread that spawns a sibling then
// immediately blocks (`memory.atomic.wait32` in `join`/`recv`) never turns
// its loop again, so the sibling's script never loads — it deadlocks. The
// fix mirrors Emscripten's PROXY_TO_PTHREAD: every worker routes
// `thread-spawn` to the MAIN thread (the only always-live agent), which
// creates the Worker. `thread-spawn` still returns the new tid
// synchronously (the wasi-threads ABI requires it); only the Worker
// construction is deferred to the main thread. node's worker_threads has
// no such constraint, so it keeps spawning siblings directly.
const SP_LOCK = 0; // i32: mutex over the ring write side
const SP_SEQ = 1; // i32: doorbell — bumped per enqueue
const SP_WRITE = 2; // i32: ring write cursor (producer, under SP_LOCK)
const SP_RING_OFF = 8; // i32 index where the (tid,startArg) ring begins
const SP_RING_CAP = 1024; // max in-flight spawn requests (pairs)
const SPAWN_CTL_INTS = SP_RING_OFF + SP_RING_CAP * 2;
const SPAWN_CTL_BYTES = SPAWN_CTL_INTS * 4;

/** Worker side: enqueue a {tid, startArg} spawn request for the main
 * thread and ring its doorbell. Never blocks on the spawn completing —
 * the new thread runs `wasi_thread_start(tid, startArg)` once the main
 * thread has created its Worker. */
function requestMainThreadSpawn(spawnCtl, tid, startArg) {
  const c = new Int32Array(spawnCtl);
  while (Atomics.compareExchange(c, SP_LOCK, 0, 1) !== 0) {
    Atomics.wait(c, SP_LOCK, 1);
  }
  try {
    const wcur = Atomics.load(c, SP_WRITE);
    const slot = SP_RING_OFF + wcur * 2;
    Atomics.store(c, slot, tid | 0);
    Atomics.store(c, slot + 1, startArg | 0);
    Atomics.store(c, SP_WRITE, (wcur + 1) % SP_RING_CAP);
    Atomics.add(c, SP_SEQ, 1);
    Atomics.notify(c, SP_SEQ);
  } finally {
    Atomics.store(c, SP_LOCK, 0);
    Atomics.notify(c, SP_LOCK, 1);
  }
}

/** Main side: drain spawn requests and create each pthread Worker on the
 * main thread's (always-live) event loop. `baseData` is the primary's
 * protocol record; each spawn overrides role/tid/startArg. Returns a
 * handle whose stop() ends the loop. */
function startSpawnService(spawnCtl, baseData) {
  const c = new Int32Array(spawnCtl);
  let read = 0;
  let last = Atomics.load(c, SP_SEQ);
  let running = true;
  const hasWaitAsync = typeof Atomics.waitAsync === "function";
  function drain() {
    const write = Atomics.load(c, SP_WRITE);
    while (read !== write) {
      const slot = SP_RING_OFF + read * 2;
      const tid = Atomics.load(c, slot);
      const startArg = Atomics.load(c, slot + 1) >>> 0;
      read = (read + 1) % SP_RING_CAP;
      spawnKaraWorkerSync(
        { ...baseData, role: "pthread", tid, startArg },
        { unref: true },
      );
    }
  }
  const done = (async () => {
    for (;;) {
      let cur = Atomics.load(c, SP_SEQ);
      if (cur === last) {
        if (hasWaitAsync) {
          const w = Atomics.waitAsync(c, SP_SEQ, last);
          if (w.async) await w.value;
        } else {
          await new Promise((r) => setTimeout(r, 0));
        }
        cur = Atomics.load(c, SP_SEQ);
      }
      if (!running) break;
      last = cur;
      drain();
    }
  })();
  return {
    stop() {
      running = false;
      Atomics.add(c, SP_SEQ, 1);
      Atomics.notify(c, SP_SEQ);
      return done;
    },
  };
}

// ── host-fn worker→main proxy (threaded builds with host fns) ──
//
// The program runs in a worker (PROXY_TO_PTHREAD), but `host fn`
// implementations are user-supplied MAIN-THREAD closures. A worker that
// calls a host fn must round-trip to the main thread synchronously: it
// publishes the call into a shared control block, wakes the main
// thread, then `Atomics.wait`s for the result. The main thread is the
// only blockable-by-design agent here (its service loop yields to the
// event loop via Atomics.waitAsync), so it executes the closure and
// notifies. One SharedArrayBuffer holds: a mutex (only one host call in
// flight — the main thread services serially), a request doorbell the
// main thread waits on, a done flag, and an 8-byte-slot payload region
// for scalar args + the return. Strings cross as (ptr, len) scalars and
// live in the shared linear memory — the main side reads them directly.
const HC_LOCK = 0; // i32: mutex (0 free, 1 held)
const HC_SEQ = 1; // i32: request counter / doorbell
const HC_DONE = 2; // i32: result-ready flag for the current request
const HC_FN = 3; // i32: HOST_FN_SIGS index of the call
const HC_ARGC = 4; // i32: argument count
const HC_PAYLOAD_OFF = 64; // 8-aligned; clears the i32 control cells
const HC_MAX_ARGS = 16; // scalar-arg ceiling (host fns take a handful)
const HC_RET_SLOT = HC_MAX_ARGS; // return value lives just past the args
const HOST_CTL_BYTES = HC_PAYLOAD_OFF + (HC_MAX_ARGS + 1) * 8;

/** Worker side: a `kara_host` import namespace whose entries marshal
 * the call across the shared control block and block until the main
 * thread writes the result. Built per worker (primary and pthreads),
 * all bound to the same shared `hostCtl`. */
function makeHostProxy(hostCtl) {
  const c = new Int32Array(hostCtl);
  const f = new Float64Array(hostCtl, HC_PAYLOAD_OFF);
  const b = new BigInt64Array(hostCtl, HC_PAYLOAD_OFF);
  const kara_host = {};
  for (let idx = 0; idx < HOST_FN_SIGS.length; idx++) {
    const sig = HOST_FN_SIGS[idx];
    kara_host[sig.name] = (...args) => {
      // Acquire the host-call mutex (block on contention).
      while (Atomics.compareExchange(c, HC_LOCK, 0, 1) !== 0) {
        Atomics.wait(c, HC_LOCK, 1);
      }
      try {
        for (let k = 0; k < args.length; k++) {
          if (sig.params[k] === "bigint") b[k] = BigInt(args[k]);
          else f[k] = Number(args[k]);
        }
        Atomics.store(c, HC_FN, idx);
        Atomics.store(c, HC_ARGC, args.length);
        Atomics.store(c, HC_DONE, 0);
        // Publish (release) and ring the doorbell.
        Atomics.add(c, HC_SEQ, 1);
        Atomics.notify(c, HC_SEQ);
        // Block this worker until the main thread posts the result.
        while (Atomics.load(c, HC_DONE) === 0) {
          Atomics.wait(c, HC_DONE, 0);
        }
        if (sig.ret === "bigint") return b[HC_RET_SLOT];
        if (sig.ret === "number") return f[HC_RET_SLOT];
        return undefined;
      } finally {
        Atomics.store(c, HC_LOCK, 0);
        Atomics.notify(c, HC_LOCK, 1);
      }
    };
  }
  return kara_host;
}

/** Main side: service host-fn calls posted by workers. Runs on the
 * main thread's event loop (Atomics.waitAsync — the main agent may be
 * non-blockable), executing each user closure with the shared memory in
 * scope so (ptr, len) string args read directly. Returns a handle whose
 * stop() unblocks and ends the loop once the program has exited. */
function startHostService(hostCtl, memory, hostImpls) {
  const c = new Int32Array(hostCtl);
  const f = new Float64Array(hostCtl, HC_PAYLOAD_OFF);
  const b = new BigInt64Array(hostCtl, HC_PAYLOAD_OFF);
  const ctx = {
    get memory() {
      return memory;
    },
    readString: (ptr, len) => readString(memory, ptr, len),
  };
  let last = Atomics.load(c, HC_SEQ);
  let running = true;
  const hasWaitAsync = typeof Atomics.waitAsync === "function";
  function serveOne() {
    const idx = Atomics.load(c, HC_FN);
    const argc = Atomics.load(c, HC_ARGC);
    const sig = HOST_FN_SIGS[idx];
    const args = [];
    for (let k = 0; k < argc; k++) {
      args.push(sig.params[k] === "bigint" ? b[k] : f[k]);
    }
    let ret;
    try {
      ret = hostImpls[sig.name](...args, ctx);
    } catch (e) {
      // A throwing host impl must not deadlock the worker — log and
      // return a zero result so the round-trip completes.
      console.error("kara: host fn `" + sig.name + "` threw:", e);
      ret = undefined;
    }
    if (sig.ret === "bigint") b[HC_RET_SLOT] = BigInt(ret ?? 0n);
    else if (sig.ret === "number") f[HC_RET_SLOT] = Number(ret ?? 0);
    Atomics.store(c, HC_DONE, 1);
    Atomics.notify(c, HC_DONE);
  }
  const done = (async () => {
    for (;;) {
      let cur = Atomics.load(c, HC_SEQ);
      if (cur === last) {
        if (hasWaitAsync) {
          const w = Atomics.waitAsync(c, HC_SEQ, last);
          if (w.async) await w.value;
        } else {
          // Engines without waitAsync: poll, yielding to the event loop
          // (the main agent can't Atomics.wait).
          await new Promise((r) => setTimeout(r, 0));
        }
        cur = Atomics.load(c, HC_SEQ);
      }
      if (!running) break;
      if (cur === last) continue; // spurious wake
      last = cur;
      serveOne();
    }
  })();
  return {
    stop() {
      running = false;
      // Wake the loop so it observes !running and returns.
      Atomics.add(c, HC_SEQ, 1);
      Atomics.notify(c, HC_SEQ);
      return done;
    },
  };
}

/** Worker-side protocol: instantiate the shared-memory module and
 * either run `_start` (primary) or `wasi_thread_start` (pthread). */
async function karaThreadWorkerMain(data, postMessageFn) {
  const { role, module, memory, tidCounter, env, tid, startArg, hostCtl, spawnCtl } =
    data;
  const imports = {
    env: { memory },
    wasi: {
      "thread-spawn": (arg) => {
        const newTid = Atomics.add(new Int32Array(tidCounter), 0, 1);
        if (nodeWorkerThreads) {
          // node: nested worker_threads start independently of the
          // (blocked) parent — spawn the sibling directly.
          spawnKaraWorkerSync(
            { ...data, role: "pthread", tid: newTid, startArg: arg },
            { unref: true },
          );
        } else {
          // browser: defer Worker construction to the main thread, which
          // is the only agent whose event loop is guaranteed live (this
          // worker is about to block in `join`/`recv`).
          requestMainThreadSpawn(spawnCtl, newTid, arg);
        }
        return newTid;
      },
    },
    wasi_snapshot_preview1: makeWasiPolyfill(() => memory, env),
  };
  // host fns: proxy each call to the main thread's service loop. hostCtl
  // is null for host-fn-free programs (no proxy needed).
  if (hostCtl) {
    imports.kara_host = makeHostProxy(hostCtl);
  }
  const instance = await WebAssembly.instantiate(module, imports);
  if (role === "primary") {
    let code = 0;
    try {
      instance.exports._start();
    } catch (e) {
      if (e instanceof KaraExit) {
        code = e.code;
      } else {
        postMessageFn({
          __karaThreads: "error",
          message: String(e && e.stack ? e.stack : e),
        });
        return;
      }
    }
    postMessageFn({ __karaThreads: "exit", code });
  } else {
    instance.exports.wasi_thread_start(tid, startArg);
  }
}

/** Detect "this module was loaded as a kara thread worker" and run the
 * protocol. No-op on the main thread, in non-kara workers, and on
 * sequential-only builds. */
async function karaMaybeRunAsThreadWorker() {
  if (WASM_THREADS_FILENAME === null) return;
  const isNode =
    typeof process !== "undefined" && !!(process.versions && process.versions.node);
  if (isNode) {
    const wt = await import("node:worker_threads");
    if (wt.isMainThread) return;
    const data = wt.workerData;
    if (!data || data.__karaThreads !== true) return;
    nodeWorkerThreads = wt;
    nodeFsSync = await import("node:fs");
    await karaThreadWorkerMain(data, (m) => wt.parentPort.postMessage(m));
    return;
  }
  const isWorkerScope =
    typeof WorkerGlobalScope !== "undefined" &&
    globalThis instanceof WorkerGlobalScope;
  if (!isWorkerScope || self.location.hash !== "#kara-thread-worker") return;
  const data = await new Promise((resolve) => {
    globalThis.addEventListener("message", (e) => resolve(e.data), {
      once: true,
    });
  });
  if (!data || data.__karaThreads !== true) return;
  await karaThreadWorkerMain(data, (m) => globalThis.postMessage(m));
  // A finished pthread's worker has nothing left to do (pool workers
  // never reach here — worker_loop doesn't return).
  if (data.role === "pthread") globalThis.close();
}
await karaMaybeRunAsThreadWorker();

/** Main-thread side of the threaded run: compile the threaded module,
 * create the shared memory (limits mirror the module's import
 * declaration exactly), spawn the primary worker, await its exit. */
async function runThreaded(hostImpls = {}, opts = {}) {
  // host fn implementations are main-thread closures bridged into the
  // worker via the synchronous proxy below — validate them up front, the
  // same contract the sequential `buildImports` enforces.
  const missing = DECLARED_IMPORTS.filter(
    (n) => typeof hostImpls?.[n] !== "function",
  );
  if (missing.length > 0) {
    throw new Error(
      "missing host fn implementation(s): " + missing.join(", "),
    );
  }
  const isNode =
    typeof process !== "undefined" && !!(process.versions && process.versions.node);
  if (isNode) {
    nodeWorkerThreads = await import("node:worker_threads");
    nodeFsSync = await import("node:fs");
  }
  const src = await defaultSource(WASM_THREADS_FILENAME);
  const bytes =
    typeof Response !== "undefined" && src instanceof Response
      ? await src.arrayBuffer()
      : src;
  const module = await WebAssembly.compile(bytes);
  const memory = new WebAssembly.Memory({
    initial: THREADS_MEM_INITIAL_PAGES,
    maximum: THREADS_MEM_MAX_PAGES,
    shared: true,
  });
  const tidCounter = new SharedArrayBuffer(4);
  new Int32Array(tidCounter)[0] = 1;
  // Builtin (compiler-emitted) host fns — phase-10 host-async producers
  // (`std.web.time.after`). These run on the main thread like user host
  // fns, but their implementation is supplied here, not by the caller, and
  // they operate over the shared linear memory through a SECOND "service"
  // instance of the same module. The service instance never runs
  // `_start`/`wasi_thread_start`; its only job is to call the channel
  // externs from a host event callback so a worker parked in `recv` wakes.
  let serviceInstance = null;
  const builtinHostImpls = {};
  if (BUILTIN_HOST_FNS.length > 0) {
    const serviceImports = {
      env: { memory },
      wasi: {
        "thread-spawn": () => {
          throw new Error("kara: service instance must not spawn threads");
        },
      },
      wasi_snapshot_preview1: makeWasiPolyfill(() => memory),
      // The service never executes program code, so it never calls a host
      // fn — but instantiation must still satisfy every kara_host import.
      kara_host: Object.fromEntries(
        HOST_FN_SIGS.map((s) => [
          s.name,
          () => {
            throw new Error("kara: service instance host fn unreachable: " + s.name);
          },
        ]),
      ),
    };
    serviceInstance = await WebAssembly.instantiate(module, serviceImports);
    // Retarget the service instance's shadow stack onto a dedicated buffer
    // so its channel_send frames can't clobber the primary worker's live
    // (parked-in-recv) frames — both default to the same linker stack.
    serviceInstance.exports.__stack_pointer.value =
      serviceInstance.exports.karac_runtime_service_stack_top();
    // __kara_timer_after(chPtr: i64 [BigInt], ms: i64 [BigInt]) -> (): the
    // channel pointer is a wasm32 address (fits a JS number); channel_send
    // takes (i32 ptr, i32 val_ptr, i64 elem_size) — a unit channel sends 0
    // bytes, so val_ptr=0, elem_size=0n. After the send we drop the sender
    // ref the producer cloned for us, closing the channel.
    builtinHostImpls["__kara_timer_after"] = (chPtr, ms) => {
      const ptr = Number(chPtr);
      setTimeout(() => {
        serviceInstance.exports.karac_runtime_channel_send(ptr, 0, 0n);
        serviceInstance.exports.karac_runtime_channel_drop_sender(ptr);
      }, Number(ms));
    };
    // __kara_animation_frames(chPtr: i64 [BigInt]) -> (): a MULTI-SHOT
    // requestAnimationFrame loop. Each frame, if the worker has drained the
    // previous tick (channel_pending == 0n), feed a fresh `()`; then re-arm.
    // The pending probe coalesces — the channel holds at most one un-consumed
    // frame token — so a slow consumer drops backlog rather than growing
    // unbounded lag. The cloned sender is owned by this loop for its lifetime
    // (never dropped: the render loop lives as long as the page). Outside a
    // browser (node tests) there is no requestAnimationFrame, so fall back to
    // a ~16ms setTimeout cadence — the channel semantics are identical.
    builtinHostImpls["__kara_animation_frames"] = (chPtr) => {
      const ptr = Number(chPtr);
      const raf = globalThis.requestAnimationFrame
        ? globalThis.requestAnimationFrame.bind(globalThis)
        : (cb) => setTimeout(cb, 16);
      const tick = () => {
        if (Number(serviceInstance.exports.karac_runtime_channel_pending(ptr)) === 0) {
          serviceInstance.exports.karac_runtime_channel_send(ptr, 0, 0n);
        }
        raf(tick);
      };
      raf(tick);
    };
    // __kara_pointer_moves(chPtr: i64 [BigInt]) -> (): a MULTI-SHOT pointer
    // input stream — the first NON-UNIT host-async producer. Registers a
    // "pointermove" listener; each event marshals (clientX, clientY) as two
    // little-endian f64s into the service instance's reusable event-scratch
    // buffer in shared memory, then channel_send copies the 16-byte
    // PointerEvent payload into the queue (vs the 0-byte `()` a timer/frame
    // producer sends — `val_ptr=scratch, elem_size=16n`). Coalesces like
    // animation_frames: feed a fresh position only once the worker has drained
    // the previous one (channel_pending == 0n), so a burst of moves collapses
    // to a sample rather than growing unbounded backlog. The cloned sender is
    // owned by the listener for its lifetime (never dropped; the listener
    // lives as long as the page). Event source: `opts.pointerTarget` (a
    // browser passes the canvas element; a node test passes an EventTarget it
    // dispatches synthetic moves on), else `globalThis` if it can
    // addEventListener. No source → no-op (the channel never fills; recv
    // blocks, exactly as a tab receiving no pointer input).
    builtinHostImpls["__kara_pointer_moves"] = (chPtr) => {
      const ptr = Number(chPtr);
      const target =
        (opts && opts.pointerTarget) ||
        (typeof globalThis.addEventListener === "function" ? globalThis : null);
      if (target === null) return;
      // PointerEvent layout: { x: f64 @ 0, y: f64 @ 8, buttons: i64 @ 16 } = 24
      // bytes — kept in sync with runtime/stdlib/web_events.kara.
      const scratch = serviceInstance.exports.karac_runtime_event_scratch();
      const onMove = (e) => {
        if (Number(serviceInstance.exports.karac_runtime_channel_pending(ptr)) !== 0) return;
        // Re-derive the view each event: a shared Memory's `.buffer` may be
        // replaced on grow, so a cached DataView could go stale.
        const dv = new DataView(memory.buffer, scratch, 24);
        // Prefer element-relative coordinates (what a canvas listener wants)
        // and fall back to viewport-relative when a synthetic event omits them.
        dv.setFloat64(0, e.offsetX ?? e.clientX ?? 0, true);
        dv.setFloat64(8, e.offsetY ?? e.clientY ?? 0, true);
        // `MouseEvent.buttons` bitmask held during the move (lets the guest gate
        // on a held button for click-drag); 0 when a synthetic event omits it.
        dv.setBigInt64(16, BigInt(e.buttons ?? 0), true);
        serviceInstance.exports.karac_runtime_channel_send(ptr, scratch, 24n);
      };
      target.addEventListener("pointermove", onMove, { passive: true });
    };

    // __kara_wheel(chPtr: i64 [BigInt]) -> (): a MULTI-SHOT wheel/scroll
    // stream, sibling of __kara_pointer_moves. Each "wheel" event marshals
    // (offsetX/clientX, offsetY/clientY, deltaX, deltaY) as four little-endian
    // f64s into the event-scratch buffer, then channel_send copies the 32-byte
    // WheelEvent payload into the queue (val_ptr=scratch, elem_size=32n).
    // Coalesces like pointer_moves (feed a fresh event only once the worker
    // drained the previous one). Registered `{ passive: true }` — the producer
    // reads the deltas but does NOT preventDefault, so it never silently
    // hijacks the page's scroll; a wheel-to-zoom demo suppresses scroll via
    // CSS (overscroll-behavior / touch-action) on its own element. Event
    // source: `opts.wheelTarget` (browser: the canvas; node test: an
    // EventTarget it dispatches synthetic wheels on), else `globalThis` if it
    // can addEventListener; no source → no-op (recv just blocks).
    builtinHostImpls["__kara_wheel"] = (chPtr) => {
      const ptr = Number(chPtr);
      const target =
        (opts && opts.wheelTarget) ||
        (typeof globalThis.addEventListener === "function" ? globalThis : null);
      if (target === null) return;
      // WheelEvent layout: { x @ 0, y @ 8, delta_x @ 16, delta_y @ 24 } = 32
      // bytes — kept in sync with runtime/stdlib/web_events.kara.
      const scratch = serviceInstance.exports.karac_runtime_event_scratch();
      const onWheel = (e) => {
        if (Number(serviceInstance.exports.karac_runtime_channel_pending(ptr)) !== 0) return;
        // Re-derive the view each event: a shared Memory's `.buffer` may be
        // replaced on grow, so a cached DataView could go stale.
        const dv = new DataView(memory.buffer, scratch, 32);
        dv.setFloat64(0, e.offsetX ?? e.clientX ?? 0, true);
        dv.setFloat64(8, e.offsetY ?? e.clientY ?? 0, true);
        dv.setFloat64(16, e.deltaX ?? 0, true);
        dv.setFloat64(24, e.deltaY ?? 0, true);
        serviceInstance.exports.karac_runtime_channel_send(ptr, scratch, 32n);
      };
      target.addEventListener("wheel", onWheel, { passive: true });
    };

    // __kara_keydown(chPtr: i64 [BigInt]) -> (): a MULTI-SHOT keyboard stream,
    // sibling of __kara_pointer_moves / __kara_wheel. Each "keydown" event
    // marshals the numeric `keyCode` as one little-endian i64 into the
    // event-scratch buffer, then channel_send copies the 8-byte KeyEvent payload
    // (val_ptr=scratch, elem_size=8n). Coalesces like the others (feed a fresh
    // event only once the worker drained the previous one). Event source:
    // `opts.keyTarget` (browser: typically window/document — keydown bubbles, so
    // no element focus is needed; node test: an EventTarget it dispatches
    // synthetic keydowns on), else `globalThis` if it can addEventListener; no
    // source → no-op (recv just blocks). Not `{ passive }` (a key handler may
    // legitimately want to preventDefault), but this listener never does.
    builtinHostImpls["__kara_keydown"] = (chPtr) => {
      const ptr = Number(chPtr);
      const target =
        (opts && opts.keyTarget) ||
        (typeof globalThis.addEventListener === "function" ? globalThis : null);
      if (target === null) return;
      // KeyEvent layout: { key_code: i64 @ 0 } = 8 bytes — kept in sync with
      // runtime/stdlib/web_events.kara.
      const scratch = serviceInstance.exports.karac_runtime_event_scratch();
      const onKey = (e) => {
        if (Number(serviceInstance.exports.karac_runtime_channel_pending(ptr)) !== 0) return;
        // Re-derive the view each event: a shared Memory's `.buffer` may be
        // replaced on grow, so a cached DataView could go stale.
        const dv = new DataView(memory.buffer, scratch, 8);
        dv.setBigInt64(0, BigInt(e.keyCode ?? e.which ?? 0), true);
        serviceInstance.exports.karac_runtime_channel_send(ptr, scratch, 8n);
      };
      target.addEventListener("keydown", onKey);
    };
  }
  // host fns: stand up the worker→main proxy (shared control block + the
  // main-thread service loop). Needed when the program declares user host
  // fns OR a builtin producer is wired. The service loop dispatches both
  // (user impls + builtinHostImpls), but only user impls are contract-
  // checked above.
  let hostCtl = null;
  let hostService = null;
  if (DECLARED_IMPORTS.length > 0 || BUILTIN_HOST_FNS.length > 0) {
    hostCtl = new SharedArrayBuffer(HOST_CTL_BYTES);
    hostService = startHostService(hostCtl, memory, {
      ...hostImpls,
      ...builtinHostImpls,
    });
  }
  const poolSize =
    THREADS_POOL_SIZE ??
    (globalThis.navigator && navigator.hardwareConcurrency) ??
    4;
  const env = ["KARAC_PAR_WORKERS=" + poolSize];
  // Browser: pthread Workers are created on the main thread (the only
  // always-live agent) via a shared spawn-request ring — a blocked
  // worker cannot load nested workers. node spawns siblings directly.
  let spawnCtl = null;
  let spawnService = null;
  if (!isNode) {
    spawnCtl = new SharedArrayBuffer(SPAWN_CTL_BYTES);
  }
  const data = {
    __karaThreads: true,
    role: "primary",
    module,
    memory,
    tidCounter,
    env,
    tid: 0,
    startArg: 0,
    hostCtl,
    spawnCtl,
  };
  if (spawnCtl) spawnService = startSpawnService(spawnCtl, data);
  try {
    const code = await new Promise((resolve, reject) => {
      const w = spawnKaraWorkerSync(data);
      const onMessage = (msg) => {
        if (msg && msg.__karaThreads === "exit") resolve(msg.code);
        else if (msg && msg.__karaThreads === "error")
          reject(new Error(msg.message));
      };
      if (nodeWorkerThreads) {
        w.on("message", onMessage);
        w.on("error", reject);
      } else {
        w.addEventListener("message", (e) => onMessage(e.data));
        w.addEventListener("error", (e) =>
          reject(e.error ?? new Error("kara thread worker error")),
        );
      }
    });
    if (code !== 0) throw new KaraExit(code);
    return { memory, threaded: true };
  } finally {
    if (hostService) await hostService.stop();
    if (spawnService) await spawnService.stop();
  }
}

/**
 * Compile + instantiate the module. `hostImpls` maps each declared
 * host fn name to its implementation; missing names throw before any
 * wasm runs. `opts.module` (a WebAssembly.Module) or `opts.bytes`
 * (BufferSource) bypass the default loader.
 * Returns { instance, exports, memory }.
 */
export async function instantiate(hostImpls = {}, opts = {}) {
  let memory;
  const imports = buildImports(hostImpls, () => memory);
  const src = opts.module ?? opts.bytes ?? (await defaultSource());
  let instance;
  if (typeof Response !== "undefined" && src instanceof Response) {
    try {
      ({ instance } = await WebAssembly.instantiateStreaming(
        src.clone(),
        imports,
      ));
    } catch {
      // Wrong Content-Type from the server — compile from bytes instead.
      const mod = await WebAssembly.compile(await src.arrayBuffer());
      instance = await WebAssembly.instantiate(mod, imports);
    }
  } else {
    const mod =
      src instanceof WebAssembly.Module ? src : await WebAssembly.compile(src);
    instance = await WebAssembly.instantiate(mod, imports);
  }
  memory = instance.exports.memory;
  return { instance, exports: karaBuildExports(instance), memory };
}

/**
 * Instantiate and run the program's entry point (`_start`). A clean
 * exit (proc_exit(0) or main returning) resolves normally; a nonzero
 * exit code rejects with KaraExit.
 *
 * On a wasm-threads build this picks the THREADED module when
 * SharedArrayBuffer + cross-origin isolation are available (running
 * `_start` in a primary worker; the resolved handle then carries only
 * `{ memory, threaded: true }` — the instance lives in the worker).
 * Otherwise it console.warns and falls back to the sequential module —
 * or throws, when the build's manifest set `[wasm] fallback = false`.
 * `opts.forceSequential` skips the pick (useful for A/B runs and
 * tests); `opts.module` / `opts.bytes` only ever feed the sequential
 * path.
 */
export async function run(hostImpls = {}, opts = {}) {
  if (WASM_THREADS_FILENAME !== null && !opts.forceSequential) {
    if (threadsSupported()) {
      return await runThreaded(hostImpls, opts);
    }
    if (THREADS_NO_FALLBACK) {
      throw new Error(
        "karac: this build requires wasm-threads (SharedArrayBuffer + " +
          "cross-origin isolation) but they are unavailable. Serve with " +
          "COOP/COEP headers (Cross-Origin-Opener-Policy: same-origin; " +
          "Cross-Origin-Embedder-Policy: require-corp). Sequential " +
          "fallback was disabled by `[wasm] fallback = false` in kara.toml.",
      );
    }
    console.warn(
      "karac: SharedArrayBuffer/cross-origin isolation unavailable; " +
        "falling back to the sequential (single-threaded) module",
    );
  }
  const handle = await instantiate(hostImpls, opts);
  try {
    handle.exports._start();
  } catch (e) {
    if (!(e instanceof KaraExit) || e.code !== 0) throw e;
  }
  return handle;
}
