#!/usr/bin/env bash
# Cartographer — regenerate the effect graph for the subject program.
#
# Calls the compiler's whole-program query surface and writes the two
# JSON envelopes into `graph.js` as `window.GRAPH`, which `viewer.html`
# loads (a plain <script> include, so the viewer opens straight from
# file:// with no server and no CORS dance).
#
#   ./cartograph.sh            # uses `karac` from PATH
#   KARAC=../../target/debug/karac ./cartograph.sh   # a local build
set -euo pipefail
cd "$(dirname "$0")"

KARAC="${KARAC:-karac}"
SRC="src/service.kara"

if ! command -v "$KARAC" >/dev/null 2>&1 && [ ! -x "$KARAC" ]; then
    echo "error: '$KARAC' not found. Install karac or set KARAC=<path>." >&2
    exit 1
fi

echo "Querying the compiler for the effect graph of $SRC ..."
EFFECTS="$("$KARAC" query effects "$SRC")"
CONCURRENCY="$("$KARAC" query concurrency "$SRC")"

cat > graph.js <<EOF
// Generated by cartograph.sh — do not edit by hand.
// The effect graph below is the COMPILER's answer about src/service.kara,
// not a hand-drawn diagram. Re-run ./cartograph.sh to refresh it.
window.GRAPH = {
  effects: $EFFECTS,
  concurrency: $CONCURRENCY
};
EOF

echo "Wrote graph.js."
echo "Open viewer.html in a browser to see the effect graph."
