//! C-header emitter for producer-mode library artifacts — the cbindgen
//! analogue (additive-interop Slice 3; design.md § Exported C ABI).
//!
//! Given a program built as a `--crate-type staticlib/cdylib`, this emits
//! a `.h` describing the exported C surface so a foreign caller
//! `#include`s it instead of hand-transcribing signatures. It is plain
//! data (AST → string, no `inkwell`), so it lives outside the
//! codegen-containment boundary and is callable on a non-`llvm` build.
//!
//! The exported surface is every `pub extern "C" fn` (see
//! [`is_exported`]); today Kāra emits bare, unmangled symbols for those,
//! so the C symbol name is the source name. The type mapping is the
//! honest v1 set from the spec: primitives + raw pointers + `#[repr(C)]`
//! structs cross transparently; everything else crosses as an opaque
//! `KaraHandle` (a `void*`), with the Kāra type named in a comment. The
//! ownership/boxing mechanics behind a handle are Slice 4 (`forget`) —
//! the header states the surface, not the handoff.

use std::collections::{BTreeMap, BTreeSet};

use crate::ast::{
    EffectItem, EffectList, EffectVerbKind, Function, Item, Program, StructDef, TypeExpr, TypeKind,
};

/// True iff `func` is part of the exported C surface: a `pub extern "C"`
/// (or `"C-unwind"`) function *definition*. `abi` is `Some` only for
/// FFI-export definitions (a body callable from C), so this does not
/// match ordinary Kāra functions or foreign imports.
pub fn is_exported(func: &Function) -> bool {
    func.is_pub && matches!(func.abi.as_deref(), Some("C") | Some("C-unwind"))
}

/// Emit the C header text for `program`'s exported surface. `lib_name` is
/// the bare library stem (no `lib` prefix / extension) — it names the
/// include guard and appears in the banner.
pub fn emit_c_header(program: &Program, lib_name: &str) -> String {
    let exports: Vec<&Function> = program
        .items
        .iter()
        .filter_map(|it| match it {
            Item::Function(f) if is_exported(f) => Some(f),
            _ => None,
        })
        .collect();

    // Index of `#[repr(C)]` structs by name — the transparent aggregate
    // set. A default-layout struct is intentionally absent (no stable C
    // layout), so it maps to an opaque handle like every other aggregate.
    let repr_c_structs: BTreeMap<&str, &StructDef> = program
        .items
        .iter()
        .filter_map(|it| match it {
            Item::StructDef(s) if is_repr_c(s) => Some((s.name.as_str(), s)),
            _ => None,
        })
        .collect();

    // Walk every exported signature, mapping each type to C and recording
    // which repr(C) structs and whether an opaque handle are referenced.
    let mut needed_structs: BTreeSet<String> = BTreeSet::new();
    let mut used_opaque = false;
    let mut protos: Vec<String> = Vec::with_capacity(exports.len());
    for f in &exports {
        protos.push(render_prototype(
            f,
            &repr_c_structs,
            &mut needed_structs,
            &mut used_opaque,
        ));
    }

    let guard = guard_macro(lib_name);
    let mut out = String::new();
    out.push_str(&format!(
        "/* Generated by karac — C ABI for the `{lib_name}` Kāra library.\n\
         * Producer-mode artifact (design.md \u{00a7} Exported C ABI). Do not edit by hand.\n\
         *\n\
         * Link: cc your_host.c -l{lib_name} -lpthread -lm -ldl -o your_host\n\
         * (the static archive bundles the Kāra runtime; a cdylib pulls it in too).\n\
         */\n"
    ));
    out.push_str(&format!("#ifndef {guard}\n#define {guard}\n\n"));
    out.push_str("#include <stdint.h>\n#include <stddef.h>\n\n");
    out.push_str("#ifdef __cplusplus\nextern \"C\" {\n#endif\n\n");

    // Runtime lifecycle — always surfaced (real symbols in the runtime
    // archive; no-ops at v1). A host calls init once before the first
    // exported call and shutdown at teardown.
    out.push_str(
        "/* Runtime lifecycle. Call karac_runtime_init() once before the first\n\
         * exported call, and karac_runtime_shutdown() at host teardown. */\n\
         void karac_runtime_init(void);\n\
         void karac_runtime_shutdown(void);\n\n",
    );

    if used_opaque {
        out.push_str(
            "/* Opaque handle to a K\u{101}ra-owned value (Vec/String/enum/non-repr(C)\n\
             * struct/...). Passed by pointer only; never dereferenced or free()d by\n\
             * the C side \u{2014} return it to a K\u{101}ra-provided destructor. */\n\
             typedef void* KaraHandle;\n\n",
        );
    }

    // repr(C) struct definitions, dependency-ordered (a struct used
    // by-value inside another must be defined first).
    if !needed_structs.is_empty() {
        let mut emitted: BTreeSet<String> = BTreeSet::new();
        let mut body = String::new();
        for name in &needed_structs {
            emit_struct(
                name,
                &repr_c_structs,
                &needed_structs,
                &mut emitted,
                &mut body,
            );
        }
        out.push_str(&body);
    }

    for proto in &protos {
        out.push_str(proto);
        out.push('\n');
    }

    out.push_str("\n#ifdef __cplusplus\n}\n#endif\n\n");
    out.push_str(&format!("#endif /* {guard} */\n"));
    out
}

/// Render one exported function's prototype, including a Doxygen-style
/// `@effects` line (producer-side effects are KNOWN — checked against the
/// body — so the header states them precisely).
fn render_prototype(
    func: &Function,
    structs: &BTreeMap<&str, &StructDef>,
    needed: &mut BTreeSet<String>,
    used_opaque: &mut bool,
) -> String {
    let ret = match &func.return_type {
        None => "void".to_string(),
        Some(ty) if is_unit(ty) => "void".to_string(),
        Some(ty) => c_type(ty, structs, needed, used_opaque),
    };
    let params: Vec<String> = func
        .params
        .iter()
        .map(|p| {
            let cty = c_type(&p.ty, structs, needed, used_opaque);
            match p.name() {
                Some(n) => format!("{cty} {n}"),
                None => cty,
            }
        })
        .collect();
    let param_list = if params.is_empty() {
        "void".to_string()
    } else {
        params.join(", ")
    };
    let mut s = String::new();
    if let Some(eff) = render_effects(func.effects.as_ref()) {
        s.push_str(&format!("/** @effects {eff} */\n"));
    }
    s.push_str(&format!("{ret} {}({param_list});", func.name));
    s
}

/// Map a Kāra type expression to its C rendering, recording referenced
/// repr(C) structs (into `needed`) and whether an opaque handle was used.
fn c_type(
    ty: &TypeExpr,
    structs: &BTreeMap<&str, &StructDef>,
    needed: &mut BTreeSet<String>,
    used_opaque: &mut bool,
) -> String {
    match &ty.kind {
        TypeKind::Unit => "void".to_string(),
        TypeKind::Tuple(elems) if elems.is_empty() => "void".to_string(),
        TypeKind::Pointer { is_mut, inner } => {
            let base = c_type(inner, structs, needed, used_opaque);
            if *is_mut {
                format!("{base}*")
            } else {
                format!("const {base}*")
            }
        }
        TypeKind::Path(path) if path.segments.len() == 1 => {
            let name = &path.segments[0];
            if let Some(prim) = c_primitive(name) {
                prim.to_string()
            } else if structs.contains_key(name.as_str()) {
                needed.insert(name.clone());
                format!("struct {name}")
            } else {
                *used_opaque = true;
                format!("KaraHandle /* {name} */")
            }
        }
        _ => {
            *used_opaque = true;
            format!("KaraHandle /* {} */", type_display(ty))
        }
    }
}

/// The C type for a Kāra primitive name, or `None` if `name` is not a
/// boundary-transparent primitive.
fn c_primitive(name: &str) -> Option<&'static str> {
    Some(match name {
        "i8" => "int8_t",
        "i16" => "int16_t",
        "i32" => "int32_t",
        "i64" => "int64_t",
        "u8" => "uint8_t",
        "u16" => "uint16_t",
        "u32" => "uint32_t",
        "u64" => "uint64_t",
        "f32" => "float",
        "f64" => "double",
        // C `_Bool` layout is not portably guaranteed across compilers;
        // `uint8_t` (0/1) is the stable boundary representation.
        "bool" => "uint8_t",
        // FFI-only size types (design.md \u{00a7} Numeric Semantics).
        "usize" => "size_t",
        "isize" => "ptrdiff_t",
        _ => return None,
    })
}

/// Emit a repr(C) struct definition into `body` in dependency order
/// (post-order DFS: a by-value struct field is defined before the struct
/// that uses it). `emitted` guards against re-emitting a shared struct.
fn emit_struct(
    name: &str,
    structs: &BTreeMap<&str, &StructDef>,
    needed: &BTreeSet<String>,
    emitted: &mut BTreeSet<String>,
    body: &mut String,
) {
    if emitted.contains(name) {
        return;
    }
    let Some(def) = structs.get(name) else {
        return;
    };
    // Emit repr(C) struct dependencies referenced by-value first.
    for field in &def.fields {
        if let TypeKind::Path(p) = &field.ty.kind {
            if p.segments.len() == 1 {
                let dep = &p.segments[0];
                if structs.contains_key(dep.as_str()) && needed.contains(dep) {
                    emit_struct(dep, structs, needed, emitted, body);
                }
            }
        }
    }
    emitted.insert(name.to_string());
    body.push_str(&format!("struct {name} {{\n"));
    for field in &def.fields {
        // Reuse the signature mapper; struct-emit-time opaque/needed
        // recording is inert here (the header-level flags are already set
        // from signature mapping), so route through throwaway sinks.
        let mut throwaway_needed = BTreeSet::new();
        let mut throwaway_opaque = false;
        let cty = c_type(
            &field.ty,
            structs,
            &mut throwaway_needed,
            &mut throwaway_opaque,
        );
        body.push_str(&format!("    {cty} {};\n", field.name));
    }
    body.push_str("};\n\n");
}

/// Render a declared effect list as a compact `verb(Resource), ...`
/// string for the `@effects` comment, or `None` when the function
/// declares no effects (pure).
fn render_effects(effects: Option<&EffectList>) -> Option<String> {
    let list = effects?;
    if list.items.is_empty() {
        return None;
    }
    let mut parts: Vec<String> = Vec::new();
    for item in &list.items {
        match item {
            EffectItem::Verb(v) => {
                let verb = verb_name(&v.kind);
                if v.resources.is_empty() {
                    parts.push(verb.to_string());
                } else {
                    let res: Vec<String> = v.resources.iter().map(|r| r.path.join(".")).collect();
                    parts.push(format!("{verb}({})", res.join(", ")));
                }
            }
            EffectItem::Group(g) => parts.push(g.clone()),
            EffectItem::Polymorphic => parts.push("_".to_string()),
            EffectItem::Variable(e) => parts.push(e.clone()),
        }
    }
    if parts.is_empty() {
        None
    } else {
        Some(parts.join(", "))
    }
}

fn verb_name(kind: &EffectVerbKind) -> String {
    match kind {
        EffectVerbKind::Reads => "reads".to_string(),
        EffectVerbKind::Writes => "writes".to_string(),
        EffectVerbKind::Sends => "sends".to_string(),
        EffectVerbKind::Receives => "receives".to_string(),
        EffectVerbKind::Allocates => "allocates".to_string(),
        EffectVerbKind::Panics => "panics".to_string(),
        EffectVerbKind::Blocks => "blocks".to_string(),
        EffectVerbKind::Suspends => "suspends".to_string(),
        EffectVerbKind::UserDefined(n) => n.clone(),
    }
}

/// True iff `ty` is the unit type (`()`), which maps to a `void` return.
fn is_unit(ty: &TypeExpr) -> bool {
    matches!(&ty.kind, TypeKind::Unit) || matches!(&ty.kind, TypeKind::Tuple(e) if e.is_empty())
}

/// True iff a struct carries `#[repr(C)]`.
fn is_repr_c(def: &StructDef) -> bool {
    use crate::ast::ExprKind;
    def.attributes.iter().any(|a| {
        a.is_bare("repr")
            && a.args.iter().any(|arg| {
                if arg.name.is_some() {
                    return false;
                }
                match arg.value.as_ref().map(|e| &e.kind) {
                    Some(ExprKind::Identifier(s)) => s == "C",
                    Some(ExprKind::Path { segments, .. }) => {
                        segments.len() == 1 && segments[0] == "C"
                    }
                    _ => false,
                }
            })
    })
}

/// A best-effort Kāra-surface rendering of a type expression for the
/// opaque-handle comment (`KaraHandle /* Vec[i32] */`).
fn type_display(ty: &TypeExpr) -> String {
    match &ty.kind {
        TypeKind::Path(p) => p.segments.join("."),
        TypeKind::Ref(inner) => format!("ref {}", type_display(inner)),
        TypeKind::MutRef(inner) => format!("mut ref {}", type_display(inner)),
        TypeKind::Pointer { is_mut, inner } => {
            let q = if *is_mut { "mut" } else { "const" };
            format!("*{q} {}", type_display(inner))
        }
        TypeKind::Tuple(elems) if elems.is_empty() => "()".to_string(),
        _ => "value".to_string(),
    }
}

/// The include-guard macro for `lib_name`: uppercased, non-alphanumerics
/// collapsed to `_`, wrapped as `LIB<NAME>_H`.
fn guard_macro(lib_name: &str) -> String {
    let mut s = String::from("LIB");
    for ch in lib_name.chars() {
        if ch.is_ascii_alphanumeric() {
            s.push(ch.to_ascii_uppercase());
        } else {
            s.push('_');
        }
    }
    s.push_str("_H");
    s
}

#[cfg(test)]
mod tests {
    use super::*;

    fn header_for(src: &str, name: &str) -> String {
        let parsed = crate::parse(src);
        emit_c_header(&parsed.program, name)
    }

    #[test]
    fn primitive_and_pointer_signature() {
        let src = "pub extern \"C\" fn saxpy(n: i64, a: f32, x: *const f32, y: *mut f32) { }";
        let h = header_for(src, "kernels");
        assert!(
            h.contains("void saxpy(int64_t n, float a, const float* x, float* y);"),
            "unexpected header:\n{h}"
        );
        // Guard + lifecycle + extern-C wrapper are always present.
        assert!(h.contains("#ifndef LIBKERNELS_H"));
        assert!(h.contains("void karac_runtime_init(void);"));
        assert!(h.contains("extern \"C\""));
    }

    #[test]
    fn no_params_renders_void() {
        let src = "pub extern \"C\" fn tick() -> i32 { 0 }";
        let h = header_for(src, "t");
        assert!(h.contains("int32_t tick(void);"), "unexpected header:\n{h}");
    }

    #[test]
    fn non_exported_fns_are_excluded() {
        // Not pub, and a pub non-extern fn — neither is part of the C surface.
        let src = "extern \"C\" fn helper() { }\npub fn compute() -> i32 { 1 }";
        let h = header_for(src, "lib");
        assert!(!h.contains("helper"), "private extern leaked:\n{h}");
        assert!(!h.contains("compute"), "non-extern pub fn leaked:\n{h}");
    }

    #[test]
    fn repr_c_struct_is_emitted() {
        let src = "#[repr(C)]\npub struct Point { x: f64, y: f64 }\n\
                   pub extern \"C\" fn origin_dist(p: Point) -> f64 { 0.0 }";
        let h = header_for(src, "geo");
        assert!(h.contains("struct Point {"), "struct missing:\n{h}");
        assert!(h.contains("double x;"), "field missing:\n{h}");
        assert!(
            h.contains("double origin_dist(struct Point p);"),
            "proto missing:\n{h}"
        );
    }

    #[test]
    fn non_transparent_type_becomes_opaque_handle() {
        let src = "pub extern \"C\" fn build() -> Vec[i32] { }";
        let h = header_for(src, "lib");
        assert!(
            h.contains("typedef void* KaraHandle;"),
            "typedef missing:\n{h}"
        );
        assert!(
            h.contains("KaraHandle /* Vec */ build(void);"),
            "proto:\n{h}"
        );
    }

    #[test]
    fn declared_effects_render_as_doc_comment() {
        let src = "pub extern \"C\" fn touch(fd: i32) with writes(FileSystem), blocks { }";
        let h = header_for(src, "io");
        assert!(
            h.contains("@effects writes(FileSystem), blocks"),
            "effects comment missing:\n{h}"
        );
    }
}
