//! `kara.lock` reader/writer.
//!
//! Slice 1 of the lockfile entry (phase-5 tracker line 831). Pure-data
//! module: types, deterministic TOML serializer, TOML parser, and error
//! variants. The integration that calls the writer after a successful
//! resolve and the reader on each subsequent build lives in slice 4
//! (`cli::run_dep_resolution`).
//!
//! Schema (v1):
//!
//! ```toml
//! # This file is auto-generated by karac.
//! # Do not edit manually.
//! version = 1
//!
//! [[package]]
//! name = "root-pkg"
//! version = "0.1.0"
//! source = "root"
//! content_hash = "blake3:..."
//! dependencies = ["child"]
//!
//! [[package]]
//! name = "child"
//! version = "0.0.0"
//! source = "path+./vendor/child"
//! content_hash = "blake3:..."
//! dependencies = []
//! ```
//!
//! Source-string vocabulary (`source = "..."`):
//! - `"root"` — the entry-point package
//! - `"path+<path>"` — local path-dep; `<path>` is relative to the project root
//! - `"registry+<url>"` — forward-compat placeholder for the registry-proxy fetch
//! - `"git+<url>"` / `"git+<url>?branch=…"` / `…?tag=…` / `…?rev=…` — forward-compat placeholder

use std::path::{Path, PathBuf};

use crate::manifest::GitRef;

/// Current lockfile schema version. Bumped when the on-disk format changes
/// in a backwards-incompatible way.
pub const LOCKFILE_SCHEMA_VERSION: u32 = 1;

/// Placeholder content-hash for sources whose real hash requires the
/// registry-proxy / git-fetch surfaces (tracker lines 835 / v1.1.x carve-out
/// (c)). Path-deps get a real BLAKE3 hash today via `compute_content_hash`;
/// registry / git entries get this sentinel until those fetches ship.
pub const PENDING_FETCH_HASH: &str = "blake3:pending-fetch";

const LOCKFILE_HEADER: &str = "# This file is auto-generated by karac.\n# Do not edit manually.\n";

/// BLAKE3 hash of arbitrary bytes, formatted as `"blake3:<64-hex>"`. The
/// caller decides what to feed in — for path-deps this is the on-disk
/// manifest TOML content as the loader consumed it.
pub fn compute_content_hash(bytes: &[u8]) -> String {
    let hash = blake3::hash(bytes);
    format!("blake3:{}", hash.to_hex())
}

/// Filesystem-touching helper: read the manifest at `path` and hash its
/// contents. Wraps IO errors as `LockfileError::Io` with the offending
/// path. Gated off `wasm32` along with the rest of the on-disk lockfile
/// surface (slice 4 plumbs this into `cli::run_dep_resolution`).
#[cfg(not(target_arch = "wasm32"))]
pub fn compute_path_dep_hash(manifest_path: &Path) -> Result<String, LockfileError> {
    let bytes = std::fs::read(manifest_path).map_err(|e| LockfileError::Io {
        path: manifest_path.to_path_buf(),
        error: e.to_string(),
    })?;
    Ok(compute_content_hash(&bytes))
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lockfile {
    pub version: u32,
    pub packages: Vec<LockedPackage>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockedPackage {
    pub name: String,
    pub version: String,
    pub source: LockSource,
    pub content_hash: String,
    pub dependencies: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum LockSource {
    Root,
    Path(PathBuf),
    Registry {
        url: String,
    },
    Git {
        url: String,
        reference: Option<GitRef>,
    },
}

#[derive(Debug)]
pub enum LockfileError {
    Io {
        path: PathBuf,
        error: String,
    },
    Parse {
        path: PathBuf,
        message: String,
    },
    SchemaVersion {
        path: PathBuf,
        found: u32,
        supported: u32,
    },
    InvalidSource {
        path: PathBuf,
        source_str: String,
    },
    InvalidField {
        path: PathBuf,
        field: String,
        message: String,
    },
}

impl LockfileError {
    pub fn code(&self) -> &'static str {
        match self {
            Self::Io { .. } => "E_LOCKFILE_IO",
            Self::Parse { .. } => "E_LOCKFILE_PARSE",
            Self::SchemaVersion { .. } => "E_LOCKFILE_SCHEMA_VERSION",
            Self::InvalidSource { .. } => "E_LOCKFILE_INVALID_SOURCE",
            Self::InvalidField { .. } => "E_LOCKFILE_INVALID_FIELD",
        }
    }
}

impl std::fmt::Display for LockfileError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Io { path, error } => {
                write!(f, "failed to read lockfile {}: {}", path.display(), error)
            }
            Self::Parse { path, message } => {
                write!(
                    f,
                    "failed to parse lockfile {}: {}",
                    path.display(),
                    message
                )
            }
            Self::SchemaVersion {
                path,
                found,
                supported,
            } => write!(
                f,
                "lockfile {} declares schema version {} but karac supports version {}",
                path.display(),
                found,
                supported,
            ),
            Self::InvalidSource { path, source_str } => write!(
                f,
                "lockfile {} contains unrecognized source string {source_str:?}",
                path.display(),
            ),
            Self::InvalidField {
                path,
                field,
                message,
            } => write!(
                f,
                "lockfile {} has invalid field {field:?}: {message}",
                path.display(),
            ),
        }
    }
}

impl std::error::Error for LockfileError {}

impl Lockfile {
    pub fn new() -> Self {
        Self {
            version: LOCKFILE_SCHEMA_VERSION,
            packages: Vec::new(),
        }
    }

    /// Parse a lockfile TOML source string. The `path` argument is used only
    /// for diagnostic provenance — nothing here touches the filesystem.
    pub fn parse(path: &Path, source: &str) -> Result<Self, LockfileError> {
        let table: toml::Table =
            source
                .parse()
                .map_err(|e: toml::de::Error| LockfileError::Parse {
                    path: path.to_path_buf(),
                    message: e.message().to_string(),
                })?;

        let version = parse_version_field(path, &table)?;
        if version != LOCKFILE_SCHEMA_VERSION {
            return Err(LockfileError::SchemaVersion {
                path: path.to_path_buf(),
                found: version,
                supported: LOCKFILE_SCHEMA_VERSION,
            });
        }

        let mut packages = Vec::new();
        if let Some(pkgs_value) = table.get("package") {
            let pkgs_array = pkgs_value
                .as_array()
                .ok_or_else(|| LockfileError::InvalidField {
                    path: path.to_path_buf(),
                    field: "package".to_string(),
                    message: "expected array of tables".to_string(),
                })?;
            for pkg_value in pkgs_array {
                let pkg_table =
                    pkg_value
                        .as_table()
                        .ok_or_else(|| LockfileError::InvalidField {
                            path: path.to_path_buf(),
                            field: "package".to_string(),
                            message: "expected table elements".to_string(),
                        })?;
                packages.push(parse_package(path, pkg_table)?);
            }
        }

        Ok(Self { version, packages })
    }

    /// Serialize to deterministic TOML. Two calls on the same `Lockfile`
    /// produce byte-identical output; this is the lockfile diff-stability
    /// invariant.
    pub fn to_toml(&self) -> String {
        let mut out = String::new();
        out.push_str(LOCKFILE_HEADER);
        out.push('\n');
        out.push_str(&format!("version = {}\n", self.version));

        let mut sorted: Vec<&LockedPackage> = self.packages.iter().collect();
        sorted.sort_by(|a, b| a.name.cmp(&b.name));

        for pkg in sorted {
            out.push('\n');
            out.push_str("[[package]]\n");
            out.push_str(&format!("name = {}\n", quote_string(&pkg.name)));
            out.push_str(&format!("version = {}\n", quote_string(&pkg.version)));
            out.push_str(&format!(
                "source = {}\n",
                quote_string(&encode_source(&pkg.source))
            ));
            out.push_str(&format!(
                "content_hash = {}\n",
                quote_string(&pkg.content_hash)
            ));

            let mut deps = pkg.dependencies.clone();
            deps.sort();
            deps.dedup();
            if deps.is_empty() {
                out.push_str("dependencies = []\n");
            } else {
                out.push_str("dependencies = [\n");
                for d in &deps {
                    out.push_str(&format!("    {},\n", quote_string(d)));
                }
                out.push_str("]\n");
            }
        }

        out
    }
}

impl Default for Lockfile {
    fn default() -> Self {
        Self::new()
    }
}

fn parse_version_field(path: &Path, table: &toml::Table) -> Result<u32, LockfileError> {
    match table.get("version") {
        Some(toml::Value::Integer(i)) => {
            u32::try_from(*i).map_err(|_| LockfileError::InvalidField {
                path: path.to_path_buf(),
                field: "version".to_string(),
                message: format!("expected non-negative integer fitting u32, got {i}"),
            })
        }
        Some(_) => Err(LockfileError::InvalidField {
            path: path.to_path_buf(),
            field: "version".to_string(),
            message: "expected integer".to_string(),
        }),
        None => Err(LockfileError::InvalidField {
            path: path.to_path_buf(),
            field: "version".to_string(),
            message: "missing required field".to_string(),
        }),
    }
}

fn parse_package(path: &Path, table: &toml::Table) -> Result<LockedPackage, LockfileError> {
    let name = expect_string_field(path, table, "name")?;
    let version = expect_string_field(path, table, "version")?;
    let source_str = expect_string_field(path, table, "source")?;
    let content_hash = expect_string_field(path, table, "content_hash")?;
    let source = decode_source(path, &source_str)?;

    let dependencies = match table.get("dependencies") {
        Some(toml::Value::Array(a)) => {
            let mut deps = Vec::new();
            for v in a {
                let s = v.as_str().ok_or_else(|| LockfileError::InvalidField {
                    path: path.to_path_buf(),
                    field: "dependencies".to_string(),
                    message: "expected array of strings".to_string(),
                })?;
                deps.push(s.to_string());
            }
            deps
        }
        Some(_) => {
            return Err(LockfileError::InvalidField {
                path: path.to_path_buf(),
                field: "dependencies".to_string(),
                message: "expected array of strings".to_string(),
            });
        }
        None => Vec::new(),
    };

    Ok(LockedPackage {
        name,
        version,
        source,
        content_hash,
        dependencies,
    })
}

fn expect_string_field(
    path: &Path,
    table: &toml::Table,
    field: &str,
) -> Result<String, LockfileError> {
    match table.get(field) {
        Some(toml::Value::String(s)) => Ok(s.clone()),
        Some(_) => Err(LockfileError::InvalidField {
            path: path.to_path_buf(),
            field: field.to_string(),
            message: "expected string".to_string(),
        }),
        None => Err(LockfileError::InvalidField {
            path: path.to_path_buf(),
            field: field.to_string(),
            message: "missing required field".to_string(),
        }),
    }
}

fn encode_source(source: &LockSource) -> String {
    match source {
        LockSource::Root => "root".to_string(),
        LockSource::Path(p) => format!("path+{}", p.display()),
        LockSource::Registry { url } => format!("registry+{url}"),
        LockSource::Git { url, reference } => match reference {
            None => format!("git+{url}"),
            Some(GitRef::Branch(b)) => format!("git+{url}?branch={b}"),
            Some(GitRef::Tag(t)) => format!("git+{url}?tag={t}"),
            Some(GitRef::Rev(r)) => format!("git+{url}?rev={r}"),
        },
    }
}

fn decode_source(path: &Path, s: &str) -> Result<LockSource, LockfileError> {
    if s == "root" {
        return Ok(LockSource::Root);
    }
    if let Some(rest) = s.strip_prefix("path+") {
        return Ok(LockSource::Path(PathBuf::from(rest)));
    }
    if let Some(rest) = s.strip_prefix("registry+") {
        return Ok(LockSource::Registry {
            url: rest.to_string(),
        });
    }
    if let Some(rest) = s.strip_prefix("git+") {
        let (url, reference) = match rest.find('?') {
            Some(idx) => {
                let url = rest[..idx].to_string();
                let query = &rest[idx + 1..];
                let reference = if let Some(b) = query.strip_prefix("branch=") {
                    Some(GitRef::Branch(b.to_string()))
                } else if let Some(t) = query.strip_prefix("tag=") {
                    Some(GitRef::Tag(t.to_string()))
                } else if let Some(r) = query.strip_prefix("rev=") {
                    Some(GitRef::Rev(r.to_string()))
                } else {
                    return Err(LockfileError::InvalidSource {
                        path: path.to_path_buf(),
                        source_str: s.to_string(),
                    });
                };
                (url, reference)
            }
            None => (rest.to_string(), None),
        };
        return Ok(LockSource::Git { url, reference });
    }
    Err(LockfileError::InvalidSource {
        path: path.to_path_buf(),
        source_str: s.to_string(),
    })
}

/// TOML basic-string escape for embedding a value in lockfile output.
fn quote_string(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for ch in s.chars() {
        match ch {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            '\t' => out.push_str("\\t"),
            c if (c as u32) < 0x20 => out.push_str(&format!("\\u{:04X}", c as u32)),
            c => out.push(c),
        }
    }
    out.push('"');
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn dummy_path() -> &'static Path {
        Path::new("kara.lock")
    }

    #[test]
    fn parse_empty_lockfile() {
        let src = "version = 1\n";
        let lockfile = Lockfile::parse(dummy_path(), src).unwrap();
        assert_eq!(lockfile.version, 1);
        assert!(lockfile.packages.is_empty());
    }

    #[test]
    fn parse_lockfile_with_packages() {
        let src = r#"version = 1

[[package]]
name = "root-pkg"
version = "0.1.0"
source = "root"
content_hash = "blake3:abc"
dependencies = ["child"]

[[package]]
name = "child"
version = "0.0.0"
source = "path+./vendor/child"
content_hash = "blake3:def"
dependencies = []
"#;
        let lf = Lockfile::parse(dummy_path(), src).unwrap();
        assert_eq!(lf.packages.len(), 2);
        assert_eq!(lf.packages[0].name, "root-pkg");
        assert_eq!(lf.packages[0].source, LockSource::Root);
        assert_eq!(lf.packages[0].dependencies, vec!["child".to_string()]);
        assert_eq!(
            lf.packages[1].source,
            LockSource::Path(PathBuf::from("./vendor/child"))
        );
    }

    #[test]
    fn parse_malformed_rejects() {
        let src = "this is not toml :::";
        let err = Lockfile::parse(dummy_path(), src).unwrap_err();
        assert!(matches!(err, LockfileError::Parse { .. }));
    }

    #[test]
    fn schema_version_mismatch() {
        let src = "version = 99\n";
        let err = Lockfile::parse(dummy_path(), src).unwrap_err();
        match err {
            LockfileError::SchemaVersion {
                found, supported, ..
            } => {
                assert_eq!(found, 99);
                assert_eq!(supported, LOCKFILE_SCHEMA_VERSION);
            }
            other => panic!("expected SchemaVersion, got {other:?}"),
        }
    }

    #[test]
    fn missing_version_field() {
        let src = r#"[[package]]
name = "foo"
version = "1.0.0"
source = "root"
content_hash = "blake3:x"
"#;
        let err = Lockfile::parse(dummy_path(), src).unwrap_err();
        match err {
            LockfileError::InvalidField { field, .. } => {
                assert_eq!(field, "version");
            }
            other => panic!("expected InvalidField, got {other:?}"),
        }
    }

    #[test]
    fn missing_required_package_field() {
        let src = r#"version = 1

[[package]]
name = "foo"
source = "root"
content_hash = "blake3:x"
"#;
        let err = Lockfile::parse(dummy_path(), src).unwrap_err();
        match err {
            LockfileError::InvalidField { field, .. } => {
                assert_eq!(field, "version");
            }
            other => panic!("expected InvalidField for missing version, got {other:?}"),
        }
    }

    #[test]
    fn unrecognized_source_string_rejected() {
        let src = r#"version = 1

[[package]]
name = "foo"
version = "0.0.0"
source = "weird+nope"
content_hash = "blake3:x"
"#;
        let err = Lockfile::parse(dummy_path(), src).unwrap_err();
        assert!(matches!(err, LockfileError::InvalidSource { .. }));
    }

    #[test]
    fn round_trip_path_dep() {
        let original = Lockfile {
            version: 1,
            packages: vec![
                LockedPackage {
                    name: "root".to_string(),
                    version: "0.1.0".to_string(),
                    source: LockSource::Root,
                    content_hash: "blake3:rootHash".to_string(),
                    dependencies: vec!["child".to_string()],
                },
                LockedPackage {
                    name: "child".to_string(),
                    version: "0.0.0".to_string(),
                    source: LockSource::Path(PathBuf::from("./vendor/child")),
                    content_hash: "blake3:childHash".to_string(),
                    dependencies: vec![],
                },
            ],
        };
        let toml = original.to_toml();
        let re_parsed = Lockfile::parse(dummy_path(), &toml).unwrap();
        assert_eq!(re_parsed.packages.len(), 2);
        // ordering is alphabetic after canonicalization
        assert_eq!(re_parsed.packages[0].name, "child");
        assert_eq!(re_parsed.packages[1].name, "root");
        assert_eq!(
            re_parsed.packages[1].dependencies,
            vec!["child".to_string()]
        );
    }

    #[test]
    fn round_trip_registry_and_git_variants() {
        let original = Lockfile {
            version: 1,
            packages: vec![
                LockedPackage {
                    name: "alpha".to_string(),
                    version: "1.2.3".to_string(),
                    source: LockSource::Registry {
                        url: "https://crates.io".to_string(),
                    },
                    content_hash: "blake3:alpha".to_string(),
                    dependencies: vec![],
                },
                LockedPackage {
                    name: "beta".to_string(),
                    version: "2.0.0".to_string(),
                    source: LockSource::Git {
                        url: "https://github.com/foo/bar".to_string(),
                        reference: Some(GitRef::Branch("main".to_string())),
                    },
                    content_hash: "blake3:beta".to_string(),
                    dependencies: vec![],
                },
                LockedPackage {
                    name: "gamma".to_string(),
                    version: "3.0.0".to_string(),
                    source: LockSource::Git {
                        url: "https://github.com/baz/qux".to_string(),
                        reference: Some(GitRef::Tag("v1.0".to_string())),
                    },
                    content_hash: "blake3:gamma".to_string(),
                    dependencies: vec![],
                },
                LockedPackage {
                    name: "delta".to_string(),
                    version: "4.0.0".to_string(),
                    source: LockSource::Git {
                        url: "https://github.com/quux/corge".to_string(),
                        reference: Some(GitRef::Rev("abc123".to_string())),
                    },
                    content_hash: "blake3:delta".to_string(),
                    dependencies: vec![],
                },
                LockedPackage {
                    name: "epsilon".to_string(),
                    version: "5.0.0".to_string(),
                    source: LockSource::Git {
                        url: "https://github.com/grault/garply".to_string(),
                        reference: None,
                    },
                    content_hash: "blake3:eps".to_string(),
                    dependencies: vec![],
                },
            ],
        };
        let toml = original.to_toml();
        let re_parsed = Lockfile::parse(dummy_path(), &toml).unwrap();
        assert_eq!(re_parsed.packages.len(), 5);
        // post-sort: alpha, beta, delta, epsilon, gamma
        let names: Vec<_> = re_parsed.packages.iter().map(|p| p.name.as_str()).collect();
        assert_eq!(names, vec!["alpha", "beta", "delta", "epsilon", "gamma"]);
        match &re_parsed.packages[0].source {
            LockSource::Registry { url } => assert_eq!(url, "https://crates.io"),
            other => panic!("expected Registry, got {other:?}"),
        }
        match &re_parsed.packages[1].source {
            LockSource::Git {
                url,
                reference: Some(GitRef::Branch(b)),
            } => {
                assert_eq!(url, "https://github.com/foo/bar");
                assert_eq!(b, "main");
            }
            other => panic!("expected Git+branch, got {other:?}"),
        }
        match &re_parsed.packages[2].source {
            LockSource::Git {
                reference: Some(GitRef::Rev(r)),
                ..
            } => assert_eq!(r, "abc123"),
            other => panic!("expected Git+rev, got {other:?}"),
        }
        match &re_parsed.packages[3].source {
            LockSource::Git {
                url,
                reference: None,
            } => assert_eq!(url, "https://github.com/grault/garply"),
            other => panic!("expected Git+no-ref, got {other:?}"),
        }
        match &re_parsed.packages[4].source {
            LockSource::Git {
                reference: Some(GitRef::Tag(t)),
                ..
            } => assert_eq!(t, "v1.0"),
            other => panic!("expected Git+tag, got {other:?}"),
        }
    }

    #[test]
    fn deterministic_output_across_writes() {
        let lockfile = Lockfile {
            version: 1,
            packages: vec![
                LockedPackage {
                    name: "z-last".to_string(),
                    version: "1.0.0".to_string(),
                    source: LockSource::Root,
                    content_hash: "blake3:z".to_string(),
                    dependencies: vec![],
                },
                LockedPackage {
                    name: "a-first".to_string(),
                    version: "1.0.0".to_string(),
                    source: LockSource::Path(PathBuf::from("a")),
                    content_hash: "blake3:a".to_string(),
                    dependencies: vec![],
                },
            ],
        };
        let out1 = lockfile.to_toml();
        let out2 = lockfile.to_toml();
        assert_eq!(out1, out2);
        // a-first sorts before z-last
        let a_idx = out1.find("a-first").expect("a-first present");
        let z_idx = out1.find("z-last").expect("z-last present");
        assert!(a_idx < z_idx);
    }

    #[test]
    fn header_comment_in_output() {
        let lockfile = Lockfile::new();
        let out = lockfile.to_toml();
        assert!(out.starts_with("# This file is auto-generated by karac.\n"));
        assert!(out.contains("# Do not edit manually."));
        assert!(out.contains("version = 1"));
    }

    #[test]
    fn dependencies_are_sorted_and_deduped_on_write() {
        let lockfile = Lockfile {
            version: 1,
            packages: vec![LockedPackage {
                name: "p".to_string(),
                version: "1.0.0".to_string(),
                source: LockSource::Root,
                content_hash: "blake3:p".to_string(),
                dependencies: vec![
                    "c".to_string(),
                    "a".to_string(),
                    "b".to_string(),
                    "a".to_string(),
                ],
            }],
        };
        let out = lockfile.to_toml();
        let a_idx = out.find("\"a\"").expect("a present");
        let b_idx = out.find("\"b\"").expect("b present");
        let c_idx = out.find("\"c\"").expect("c present");
        assert!(a_idx < b_idx);
        assert!(b_idx < c_idx);
        assert_eq!(out.matches("\"a\"").count(), 1);
    }

    #[test]
    fn quote_string_escapes_special_chars() {
        assert_eq!(quote_string("foo"), "\"foo\"");
        assert_eq!(quote_string("a\"b"), "\"a\\\"b\"");
        assert_eq!(quote_string("a\\b"), "\"a\\\\b\"");
        assert_eq!(quote_string("a\nb"), "\"a\\nb\"");
    }

    #[test]
    fn error_code_stability() {
        let cases: &[(LockfileError, &str)] = &[
            (
                LockfileError::Io {
                    path: PathBuf::new(),
                    error: String::new(),
                },
                "E_LOCKFILE_IO",
            ),
            (
                LockfileError::Parse {
                    path: PathBuf::new(),
                    message: String::new(),
                },
                "E_LOCKFILE_PARSE",
            ),
            (
                LockfileError::SchemaVersion {
                    path: PathBuf::new(),
                    found: 0,
                    supported: 1,
                },
                "E_LOCKFILE_SCHEMA_VERSION",
            ),
            (
                LockfileError::InvalidSource {
                    path: PathBuf::new(),
                    source_str: String::new(),
                },
                "E_LOCKFILE_INVALID_SOURCE",
            ),
            (
                LockfileError::InvalidField {
                    path: PathBuf::new(),
                    field: String::new(),
                    message: String::new(),
                },
                "E_LOCKFILE_INVALID_FIELD",
            ),
        ];
        for (err, expected) in cases {
            assert_eq!(err.code(), *expected);
        }
    }

    #[test]
    fn default_lockfile_is_empty_and_versioned() {
        let lf = Lockfile::default();
        assert_eq!(lf.version, LOCKFILE_SCHEMA_VERSION);
        assert!(lf.packages.is_empty());
    }

    #[test]
    fn content_hash_is_stable() {
        let bytes = b"name = \"foo\"\nversion = \"0.1.0\"\n";
        let h1 = compute_content_hash(bytes);
        let h2 = compute_content_hash(bytes);
        assert_eq!(h1, h2);
    }

    #[test]
    fn content_hash_changes_on_edit() {
        let h1 = compute_content_hash(b"name = \"foo\"\n");
        let h2 = compute_content_hash(b"name = \"bar\"\n");
        assert_ne!(h1, h2);
    }

    #[test]
    fn content_hash_format_pin() {
        let h = compute_content_hash(b"abc");
        assert!(h.starts_with("blake3:"));
        let hex = &h["blake3:".len()..];
        // BLAKE3 default output is 32 bytes → 64 hex chars
        assert_eq!(hex.len(), 64);
        assert!(hex
            .chars()
            .all(|c| c.is_ascii_hexdigit() && !c.is_ascii_uppercase()));
    }

    #[test]
    fn content_hash_empty_input() {
        // The empty-input hash is BLAKE3's known empty-vector digest. We don't
        // pin the exact value (BLAKE3 isn't going to change), but the format
        // and length invariants still hold for the empty-bytes edge case.
        let h = compute_content_hash(&[]);
        assert!(h.starts_with("blake3:"));
        assert_eq!(h.len(), "blake3:".len() + 64);
    }

    #[test]
    fn pending_fetch_hash_format() {
        assert_eq!(PENDING_FETCH_HASH, "blake3:pending-fetch");
        assert!(PENDING_FETCH_HASH.starts_with("blake3:"));
    }

    #[cfg(not(target_arch = "wasm32"))]
    #[test]
    fn compute_path_dep_hash_reads_file() {
        use std::io::Write;

        let dir = std::env::temp_dir().join(format!(
            "karac-lockfile-hash-test-{}",
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let manifest = dir.join("kara.toml");
        {
            let mut f = std::fs::File::create(&manifest).unwrap();
            writeln!(f, "name = \"hashtest\"").unwrap();
        }
        let h = compute_path_dep_hash(&manifest).unwrap();
        let direct = compute_content_hash(b"name = \"hashtest\"\n");
        assert_eq!(h, direct);
        std::fs::remove_dir_all(&dir).ok();
    }

    #[cfg(not(target_arch = "wasm32"))]
    #[test]
    fn compute_path_dep_hash_io_error() {
        let missing = std::path::PathBuf::from("/nonexistent/karac-lockfile-test-missing.toml");
        let err = compute_path_dep_hash(&missing).unwrap_err();
        assert!(matches!(err, LockfileError::Io { .. }));
        assert_eq!(err.code(), "E_LOCKFILE_IO");
    }
}
